language: node_js
sudo: true
sudo: required
dist: trusty
addons:
  ssh_known_hosts: robotscostrent.com
notifications:
  email: false
node_js:
- '4'
- '5'
- node
before_install:
- bash .travis/scripts/before_install.sh
after_success:
- bash .travis/scripts/deploy.sh
