language: node_js
node_js:
- '4'
- '5'
- node
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_4ad8f554306a_key -iv $encrypted_4ad8f554306a_iv -in things-deploy.enc -out ~\/.ssh/things-deploy -d
script:
  - bash scripts/build.sh
after_success:
  - bash scripts/deploy.sh
