language: node_js
sudo: required
dist: trusty
addons:
  ssh_known_hosts: robotscostrent.com
notifications:
  email: false
before_install:
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_4ad8f554306a_key -iv $encrypted_4ad8f554306a_iv -in things-deploy.enc -out ~/.ssh/things-deploy -d
script:
  - ls -al ~/.ssh
  - npm test
  - npm run build:prod
node_js:
  - '4'
  - '5'
  - node
after_success:
  - bash .travis/scripts/deploy.sh
