language: node_js
addons:
  ssh_known_hosts: robotscostrent.com
node_js:
- '4'
- '5'
- node
sudo: false
before_install:
- bash .travis/scripts/before_install.sh
script:
- bash .travis/scripts/build.sh
after_success:
- bash .travis/scripts/deploy.sh
